# Generated by Django 5.2.5 on 2025-08-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="deliveries/"),
        ),
    ]
