# Generated by Django 5.0 on 2025-10-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_deliverynotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotification',
            name='notification_type',
            field=models.CharField(choices=[('approaching', 'Aproximándose'), ('leaving', 'Saliendo'), ('arriving_soon', 'Llegando pronto (3 min)'), ('arrived', 'Ha llegado'), ('delivered', 'Entregado'), ('rescheduled', 'Reprogramado')], max_length=20),
        ),
    ]
