# Generated by Django 5.0 on 2025-10-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_deliverynotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotification',
            name='notification_type',
            field=models.CharField(choices=[('approaching', 'Aproximándose'), ('leaving', 'Saliendo'), ('arriving_soon', 'Llegando pronto (3 min)'), ('arrived', 'Ha llegado'), ('delivered', 'Entregado'), ('rescheduled', 'Reprogramado'), ('failed', 'Entrega Fallida')], max_length=20),
        ),
    ]
