# Generated by Django 5.0 on 2025-11-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_deliverynotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotification',
            name='notification_type',
            field=models.CharField(choices=[('approaching', 'Aproximándose'), ('leaving', 'Saliendo'), ('arriving_soon', 'Llegando pronto (3 min)'), ('arrived', 'Ha llegado'), ('delivered', 'Entregado'), ('rescheduled', 'Reprogramado'), ('failed', 'Entrega Fallida'), ('coordinator_rescheduled', 'Reprogramación - Coordinador'), ('coordinator_status_changed', 'Cambio de Estado - Coordinador'), ('coordinator_rider_assigned', 'Asignación de Repartidor - Coordinador'), ('coordinator_schedule_changed', 'Cambio de Programación - Coordinador'), ('coordinator_delivery_failed', 'Entrega Fallida - Coordinador')], max_length=35),
        ),
    ]
