# Generated by Django 5.0 on 2025-11-04 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_deliverynotification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFailureReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('ausencia_personal', 'Ausencia de personal en destino'), ('error_direccion', 'Error en la dirección'), ('direccion_inexistente', 'Dirección no existe'), ('cliente_no_responde', 'Cliente no responde'), ('acceso_denegado', 'Acceso denegado al edificio/ubicación'), ('producto_daniado', 'Producto dañado'), ('documentacion_incompleta', 'Documentación incompleta'), ('cliente_rechazo', 'Cliente rechazó la entrega'), ('problema_vehiculo', 'Problema con el vehículo'), ('condiciones_climaticas', 'Condiciones climáticas adversas'), ('otra', 'Otra razón')], max_length=50)),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales sobre la razón del fallo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Número de intento de entrega')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_reasons', to='orders.delivery')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_failures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Razón de Fallo de Entrega',
                'verbose_name_plural': 'Razones de Fallo de Entregas',
                'ordering': ['-created_at'],
            },
        ),
    ]
